### ISSUE TITLE
dll

### ISSUE THREAD

**Issue by HongyiNet** [sundeepChandhoke/LVKafka#1]
Hello
Could you upload the dll file?
Thanks

**Comment by kunixYao** [comment]
Thanks for your code.But I can not find the dll file, could you pls upload it ,thank you all the same.

**Comment by sundeepChandhoke** [comment]
I added LV 2019 and win64 binaries.

**Comment by kunixYao** [comment]
I have downloaded the master branch, and files can not find:
_readType.ctl
_kafkaEventsToWaveform.vi
_creatKafkaEvents.vi
_extractWaveform.vi
_extractWaveformProperties.vi
_getStartingIndex.vi
_getWaveformContext.vi
Find Item.vi
Get Array Elements.vi
From JSON test.vim
JSON text to Variant.vi

Could you pls upload them?thanks.

**Comment by sundeepChandhoke** [comment]
I added these files to the main  branch under DataModeling/Support
