### ISSUE TITLE
Request for KafkaLV.dll

### ISSUE THREAD

**Issue by saiyxin** [sundeepChandhoke/LVKafka#3]
Hello, I'm very glad to find this KafkaLV API, do these APIs have been tested?I download it and but find all the VIs are broken because missing the KafkaLV.dll. Could you provide it? I'm very grateful for your help.My email is 352580609@qq.com, or you can upload to the repository. Thank you!

**Comment by sundeepChandhoke** [comment]
The DLL is in the master branch
https://github.com/sundeepChandhoke/LVKafka/tree/master/x64
