### ISSUE TITLE
Some questions for help

### ISSUE THREAD

**Issue by saiyxin** [sundeepChandhoke/LVKafka#4]
Hi，when I run the SimpleConsumer and SimpleProducer，nothing seems to have happened，Consumer reads noting and no error occur which can heip me find the reason. 
1）I wonder which kafka version does this API use？Will it be caused by different versions？
2）I find the SimpleConsumer can't stop(when I call the Kafka_ConsumerExitLoop API, it can stop. Can it act as tcp read(while there is noting read return timeout)
3）It will take about 10 seconds while using LVsend API？It seems too long.
I'm looking forward to your reply，thank you very much！

**Comment by sundeepChandhoke** [comment]
This is built on top of rdkafka ... so it should work with Kafka 2.x or greater
So the SimpleConsumer example is written to read the entire topic (from the beginning).  The way it works is you use SimpleProducer to send some data to a topic/partition and use SimpleConsumer to read it back.  The ExitLoop API is used for reading new updates to a topic/partition in real time.  You have the DLL source code so you should be able to trace the calls.

**Comment by saiyxin** [comment]
> 
I find you name the consumer ID "semi_adv", but how to configure the consumer ID and consumer group ID by using the API？ There is a long string named consumer handle while call the KafkaLVLib.dll:KafkaCreateConsumer，what does it mean，does it include some parameters？Thanks for your answer！
