### ISSUE TITLE
how to configure the consumer group ID？

### ISSUE THREAD

**Issue by saiyxin** [sundeepChandhoke/LVKafka#5]
Now the example can run successfully, I find you name the consumer ID "semi_adv", but how to configure the consumer ID and consumer group ID by using the API？ There is a long string named consumer handle while call the KafkaLVLib.dll:KafkaCreateConsumer，does it include some parameters？

I‘m not very  familiar with c++, cause there is not a whole VS sln project, when I repackage the LibLVKafka.dll, it was not successful. Need I include the rdkafka.lib(x64 or x32?) in the project? I can't find the rdkafka.lib(only rdkafka.h in the include folder ) in the repository. Could you provide the sln or the included lib？ Thank you very much！

**Comment by sundeepChandhoke** [comment]
You should be able to get the lib from here:  https://www.nuget.org/packages/librdkafka.redist/

I may not have exposed the consumer ID as an API call.  You will need to add that if you need to change it programmatically.
